# Especificación de App Platform de DigitalOcean
name: tabletop-mastering
region: nyc

# Base de datos MongoDB
databases:
  - name: tabletop-mongodb
    engine: MONGODB
    version: "7"
    size: db-s-1vcpu-1gb
    num_nodes: 1
    production: true

# Servicios
services:
  # Backend API
  - name: backend
    github:
      repo: Trevictus/TabletopMastering
      branch: main
      deploy_on_push: true
    dockerfile_path: backend/Dockerfile.prod
    source_dir: backend
    
    http_port: 5000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGODB_URI
        scope: RUN_TIME
        type: SECRET
      - key: CLIENT_URL
        scope: RUN_TIME
        value: ${APP_URL}
    
    routes:
      - path: /api
        preserve_path_prefix: true
      - path: /health

  # Frontend
  - name: frontend
    github:
      repo: Trevictus/TabletopMastering
      branch: main
      deploy_on_push: true
    dockerfile_path: frontend/Dockerfile.prod
    source_dir: frontend
    
    http_port: 80
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    build_command: npm run build
    
    health_check:
      http_path: /health
      initial_delay_seconds: 20
      period_seconds: 30
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: VITE_API_URL
        value: /api
    
    routes:
      - path: /

# Configuración de alertas
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
